/**
 * Extra E-codes beyond the current Annex II working inventory.
 *
 * bucket:
 * - annex_nf — still printed in Annex II, food use expired
 * - alias — label group code for an authorised family
 * - withdrawn — once an EU food E-number, not authorised now
 * - feed — feed/antibiotic code, never EU human-food use
 * - cited — widely typed as an E-number (Wikipedia/INS); not an official EU food E
 *
 * Names are the same substance in EN and DE. Wikipedia disagreements are
 * resolved in overlay reasons, not by swapping the chemical per language.
 *
 * @typedef {"annex_nf" | "alias" | "withdrawn" | "feed" | "cited"} Bucket
 * @typedef {{ code: string; en: string; de: string; bucket: Bucket; source?: "1831" | "hist" }} Extra
 * @type {Extra[]}
 */
export const EXTRAS = [
  { code: "E556", en: "Calcium aluminium silicate", de: "Calciumaluminiumsilicat", bucket: "annex_nf" },
  { code: "E558", en: "Bentonite", de: "Bentonit", bucket: "annex_nf" },
  { code: "E559", en: "Aluminium silicate (kaolin)", de: "Aluminiumsilicat (Kaolin)", bucket: "annex_nf" },

  { code: "E960", en: "Steviol glycosides", de: "Steviolglycoside", bucket: "alias" },

  { code: "E103", en: "Acid Orange 6", de: "Acid Orange 6", bucket: "withdrawn" },
  { code: "E105", en: "Fast Yellow AB", de: "Echtgelb", bucket: "withdrawn" },
  { code: "E111", en: "Orange GGN", de: "Orange GGN", bucket: "withdrawn" },
  { code: "E121", en: "Orcein", de: "Orcein", bucket: "withdrawn" },
  { code: "E125", en: "Scarlet GN", de: "Scharlach GN", bucket: "withdrawn" },
  { code: "E126", en: "Ponceau 6R", de: "Ponceau 6R", bucket: "withdrawn" },
  { code: "E128", en: "Red 2G", de: "Rot 2G", bucket: "withdrawn" },
  { code: "E130", en: "Indanthrene Blue RS", de: "Anthrachinonblau", bucket: "withdrawn" },
  { code: "E152", en: "Black 7984", de: "Schwarz 7984", bucket: "withdrawn" },
  { code: "E154", en: "Brown FK", de: "Braun FK", bucket: "withdrawn" },
  { code: "E160f", en: "Ethyl ester of beta-apo-8'-carotenoic acid", de: "Beta-apo-8-Carotinsäureethylester", bucket: "withdrawn" },
  { code: "E161a", en: "Flavoxanthin", de: "Flavoxanthin", bucket: "withdrawn" },
  { code: "E161c", en: "Cryptoxanthin", de: "Kryptoxanthin", bucket: "withdrawn" },
  { code: "E161d", en: "Rubixanthin", de: "Rubixanthin", bucket: "withdrawn" },
  { code: "E161e", en: "Violaxanthin", de: "Violaxanthin", bucket: "withdrawn" },
  { code: "E161f", en: "Rhodoxanthin", de: "Rhodoxanthin", bucket: "withdrawn" },
  { code: "E181", en: "Burnt umber", de: "Gebrannte Schwarzerde", bucket: "withdrawn" },
  { code: "E201", en: "Sodium sorbate", de: "Natriumsorbat", bucket: "withdrawn" },
  { code: "E203", en: "Calcium sorbate", de: "Calciumsorbat", bucket: "withdrawn" },
  { code: "E216", en: "Propyl p-hydroxybenzoate", de: "Propyl-p-hydroxybenzoat", bucket: "withdrawn" },
  { code: "E217", en: "Sodium propyl p-hydroxybenzoate", de: "Natriumpropyl-p-hydroxybenzoat", bucket: "withdrawn" },
  { code: "E225", en: "Potassium sulphite", de: "Kaliumsulfit", bucket: "withdrawn" },
  { code: "E230", en: "Biphenyl", de: "Biphenyl", bucket: "withdrawn" },
  { code: "E231", en: "Orthophenylphenol", de: "Orthophenylphenol", bucket: "withdrawn" },
  { code: "E232", en: "Sodium orthophenylphenol", de: "Natriumorthophenylphenol", bucket: "withdrawn" },
  { code: "E233", en: "Thiabendazole", de: "Thiabendazol", bucket: "withdrawn" },
  { code: "E236", en: "Formic acid", de: "Ameisensäure", bucket: "withdrawn" },
  { code: "E237", en: "Sodium formate", de: "Natriumformiat", bucket: "withdrawn" },
  { code: "E238", en: "Calcium formate", de: "Calciumformiat", bucket: "withdrawn" },
  { code: "E303", en: "Potassium ascorbate", de: "Kaliumascorbat", bucket: "withdrawn" },
  { code: "E311", en: "Octyl gallate", de: "Octylgallat", bucket: "withdrawn" },
  { code: "E312", en: "Dodecyl gallate", de: "Dodecylgallat", bucket: "withdrawn" },
  { code: "E408", en: "Furcellaran", de: "Furcellaran", bucket: "withdrawn" },
  { code: "E411", en: "Oat gum", de: "Hafergummi", bucket: "withdrawn" },
  { code: "E470", en: "Salts of fatty acids", de: "Salze der Speisefettsäuren", bucket: "withdrawn" },

  { code: "E161h", en: "Zeaxanthin", de: "Zeaxanthin", bucket: "feed", source: "1831" },
  { code: "E161i", en: "Citranaxanthin", de: "Citranaxanthin", bucket: "feed", source: "1831" },
  { code: "E161j", en: "Astaxanthin", de: "Astaxanthin", bucket: "feed", source: "1831" },
  { code: "E161y", en: "Astaxanthin-rich Phaffia rhodozyma", de: "Astaxanthinreiche Phaffia rhodozyma", bucket: "feed", source: "1831" },
  { code: "E240", en: "Formaldehyde", de: "Formaldehyd", bucket: "feed", source: "1831" },
  { code: "E295", en: "Ammonium formate", de: "Ammoniumformiat", bucket: "feed", source: "1831" },
  { code: "E324", en: "Ethoxyquin", de: "Ethoxyquin", bucket: "feed", source: "1831" },
  { code: "E484", en: "Glyceryl polyethylene glycol ricinoleate", de: "Glycerylpolyethylenglycolricinoleat", bucket: "feed", source: "1831" },
  { code: "E487", en: "Polyethylene glycol esters of fatty acids", de: "Polyethylenglycolester von Fettsäuren", bucket: "feed", source: "1831" },
  { code: "E510", en: "Ammonium chloride", de: "Ammoniumchlorid", bucket: "feed", source: "1831" },
  { code: "E551a", en: "Silicic acid, precipitated and dried", de: "Kieselsäure, gefällt und getrocknet", bucket: "feed", source: "1831" },
  { code: "E551b", en: "Colloidal silica", de: "Kolloidales Siliciumdioxid", bucket: "feed", source: "1831" },
  { code: "E551c", en: "Kieselgur (diatomaceous earth)", de: "Kieselgur", bucket: "feed", source: "1831" },
  { code: "E560", en: "Natural mixtures of steatites and chlorite", de: "Natürliche Gemische aus Steatit und Chlorit", bucket: "feed", source: "1831" },
  { code: "E561", en: "Vermiculite", de: "Vermiculit", bucket: "feed", source: "1831" },
  { code: "E562", en: "Sepiolite", de: "Sepiolith", bucket: "feed", source: "1831" },
  { code: "E563", en: "Sepiolitic clay", de: "Sepiolithton", bucket: "feed", source: "1831" },
  { code: "E565", en: "Lignosulfonates", de: "Lignosulfonate", bucket: "feed", source: "1831" },
  { code: "E566", en: "Natrolite-phonolite", de: "Natrolith-Phonolith", bucket: "feed", source: "1831" },
  { code: "E567", en: "Clinoptilolite of volcanic origin", de: "Klinoptilolith vulkanischen Ursprungs", bucket: "feed", source: "1831" },
  { code: "E568", en: "Clinoptilolite of sedimentary origin", de: "Klinoptilolith sedimentären Ursprungs", bucket: "feed", source: "1831" },
  { code: "E598", en: "Synthetic calcium aluminates", de: "Synthetische Calciumaluminate", bucket: "feed", source: "1831" },
  { code: "E599", en: "Perlite", de: "Perlit", bucket: "feed", source: "1831" },
  { code: "E670a", en: "25-Hydroxycholecalciferol", de: "25-Hydroxycholecalciferol", bucket: "feed", source: "1831" },
  { code: "E671", en: "Vitamin D3", de: "Vitamin D3", bucket: "feed", source: "1831" },
  { code: "E672", en: "Vitamin A", de: "Vitamin A", bucket: "feed", source: "1831" },
  { code: "E700", en: "Sodium benzoate / propionic acid / sodium propionate", de: "Natriumbenzoat / Propionsäure / Natriumpropionat", bucket: "feed", source: "1831" },
  { code: "E701", en: "Tetracyclines", de: "Tetracycline", bucket: "feed" },
  { code: "E702", en: "Chlortetracycline", de: "Chlortetracyclin", bucket: "feed" },
  { code: "E703", en: "Oxytetracycline", de: "Oxytetracyclin", bucket: "feed" },
  { code: "E704", en: "Oleandomycin", de: "Oleandomycin", bucket: "feed" },
  { code: "E705", en: "Penicillin G potassium", de: "Penicillin-G-Kalium", bucket: "feed" },
  { code: "E706", en: "Penicillin G sodium", de: "Penicillin-G-Natrium", bucket: "feed" },
  { code: "E707", en: "Penicillin G procaine", de: "Penicillin-G-Procain", bucket: "feed" },
  { code: "E708", en: "Penicillin G benzathine", de: "Penicillin-G-Benzathin", bucket: "feed" },
  { code: "E710", en: "Spiramycins", de: "Spiramycine", bucket: "feed" },
  { code: "E711", en: "Virginiamycins", de: "Virginiamycine", bucket: "feed" },
  { code: "E712", en: "Flavomycin", de: "Flavomycin", bucket: "feed" },
  { code: "E713", en: "Tylosin", de: "Tylosin", bucket: "feed" },
  { code: "E714", en: "Monensin A", de: "Monensin A", bucket: "feed" },
  { code: "E715", en: "Avoparcin", de: "Avoparcin", bucket: "feed" },
  { code: "E716", en: "Salinomycin", de: "Salinomycin", bucket: "feed" },
  { code: "E717", en: "Avilamycin", de: "Avilamycin", bucket: "feed" },
  { code: "E756", en: "Decoquinate", de: "Decoquinat", bucket: "feed", source: "1831" },
  { code: "E758", en: "Robenidine hydrochloride", de: "Robenidinhydrochlorid", bucket: "feed", source: "1831" },
  { code: "E763", en: "Lasalocid A sodium", de: "Lasalocid-A-Natrium", bucket: "feed", source: "1831" },
  { code: "E764", en: "Halofuginone", de: "Halofuginon", bucket: "feed", source: "1831" },
  { code: "E765", en: "Narasin", de: "Narasin", bucket: "feed", source: "1831" },
  { code: "E766", en: "Salinomycin sodium", de: "Salinomycin-Natrium", bucket: "feed", source: "1831" },
  { code: "E770", en: "Maduramicin ammonium", de: "Maduramicin-Ammonium", bucket: "feed", source: "1831" },
  { code: "E771", en: "Diclazuril", de: "Diclazuril", bucket: "feed", source: "1831" },
  { code: "E772", en: "Narasin-nicarbazin", de: "Narasin-Nicarbazin", bucket: "feed", source: "1831" },
  { code: "E773", en: "Semduramicin sodium", de: "Semduramicin-Natrium", bucket: "feed", source: "1831" },
  { code: "E1601", en: "Endo-1,3(4)-beta-glucanase / endo-1,4-beta-xylanase", de: "Endo-1,3(4)-beta-Glucanase / Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1602", en: "Endo-1,4-beta-glucanase / endo-1,3(4)-beta-glucanase / endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Glucanase / Endo-1,3(4)-beta-Glucanase / Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1603", en: "Endo-1,3(4)-beta-glucanase", de: "Endo-1,3(4)-beta-Glucanase", bucket: "feed", source: "1831" },
  { code: "E1604", en: "Endo-1,3(4)-beta-glucanase / endo-1,4-beta-xylanase", de: "Endo-1,3(4)-beta-Glucanase / Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1606", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1607", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1612", en: "Endo-1,3(4)-beta-glucanase / endo-1,4-beta-xylanase", de: "Endo-1,3(4)-beta-Glucanase / Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1613", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1614", en: "6-Phytase", de: "6-Phytase", bucket: "feed", source: "1831" },
  { code: "E1616", en: "Endo-1,4-beta-glucanase", de: "Endo-1,4-beta-Glucanase", bucket: "feed", source: "1831" },
  { code: "E1617", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1620", en: "Endo-1,3(4)-beta-glucanase (enzyme mix)", de: "Endo-1,3(4)-beta-Glucanase (Enzymmischung)", bucket: "feed", source: "1831" },
  { code: "E1621", en: "Endo-1,3(4)-beta-glucanase (enzyme mix)", de: "Endo-1,3(4)-beta-Glucanase (Enzymmischung)", bucket: "feed", source: "1831" },
  { code: "E1625", en: "Endo-1,3(4)-beta-glucanase", de: "Endo-1,3(4)-beta-Glucanase", bucket: "feed", source: "1831" },
  { code: "E1628", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1632", en: "3-Phytase", de: "3-Phytase", bucket: "feed", source: "1831" },
  { code: "E1634", en: "Endo-1,3(4)-beta-glucanase", de: "Endo-1,3(4)-beta-Glucanase", bucket: "feed", source: "1831" },
  { code: "E1636", en: "Endo-1,3(4)-beta-glucanase", de: "Endo-1,3(4)-beta-Glucanase", bucket: "feed", source: "1831" },
  { code: "E1639", en: "3-Phytase", de: "3-Phytase", bucket: "feed", source: "1831" },
  { code: "E1641", en: "Endo-1,4-beta-xylanase", de: "Endo-1,4-beta-Xylanase", bucket: "feed", source: "1831" },
  { code: "E1700", en: "Bacillus licheniformis / Bacillus subtilis", de: "Bacillus licheniformis / Bacillus subtilis", bucket: "feed", source: "1831" },
  { code: "E1701", en: "Bacillus cereus var. toyoi", de: "Bacillus cereus var. toyoi", bucket: "feed", source: "1831" },
  { code: "E1702", en: "Saccharomyces cerevisiae NCYC Sc 47", de: "Saccharomyces cerevisiae NCYC Sc 47", bucket: "feed", source: "1831" },
  { code: "E1703", en: "Saccharomyces cerevisiae CNCM I-1079", de: "Saccharomyces cerevisiae CNCM I-1079", bucket: "feed", source: "1831" },
  { code: "E1704", en: "Saccharomyces cerevisiae CBS 493.94", de: "Saccharomyces cerevisiae CBS 493.94", bucket: "feed", source: "1831" },
  { code: "E1705", en: "Enterococcus faecium NCIMB 10415", de: "Enterococcus faecium NCIMB 10415", bucket: "feed", source: "1831" },
  { code: "E1706", en: "Enterococcus faecium / Lactobacillus rhamnosus", de: "Enterococcus faecium / Lactobacillus rhamnosus", bucket: "feed", source: "1831" },
  { code: "E1707", en: "Enterococcus faecium DSM 10663 / NCIMB 10415", de: "Enterococcus faecium DSM 10663 / NCIMB 10415", bucket: "feed", source: "1831" },
  { code: "E1708", en: "Enterococcus faecium NCIMB 11181", de: "Enterococcus faecium NCIMB 11181", bucket: "feed", source: "1831" },
  { code: "E1710", en: "Saccharomyces cerevisiae MUCL 39885", de: "Saccharomyces cerevisiae MUCL 39885", bucket: "feed", source: "1831" },
  { code: "E1711", en: "Saccharomyces cerevisiae CNCM I-1077", de: "Saccharomyces cerevisiae CNCM I-1077", bucket: "feed", source: "1831" },
  { code: "E1712", en: "Pediococcus acidilactici CNCM MA 18/5M", de: "Pediococcus acidilactici CNCM MA 18/5M", bucket: "feed", source: "1831" },
  { code: "E1713", en: "Enterococcus faecium CECT 4515", de: "Enterococcus faecium CECT 4515", bucket: "feed", source: "1831" },
  { code: "E1714", en: "Lactobacillus farciminis CNCM MA 67/AR", de: "Lactobacillus farciminis CNCM MA 67/AR", bucket: "feed", source: "1831" },
  { code: "E1715", en: "Lactobacillus acidophilus D2/CSL CECT 4529", de: "Lactobacillus acidophilus D2/CSL CECT 4529", bucket: "feed", source: "1831" },

  { code: "E106", en: "Riboflavin-5-sodium phosphate", de: "Riboflavin-5-natriumphosphat", bucket: "cited" },
  { code: "E107", en: "Yellow 2G", de: "Gelb 2G", bucket: "cited" },
  { code: "E143", en: "Fast Green FCF", de: "Fast Green FCF", bucket: "cited" },
  { code: "E164", en: "Saffron", de: "Safran", bucket: "cited" },
  { code: "E182", en: "Orcein", de: "Orcein", bucket: "cited" },
  { code: "E209", en: "Heptyl p-hydroxybenzoate", de: "Heptyl-p-hydroxybenzoat", bucket: "cited" },
  { code: "E264", en: "Ammonium acetate", de: "Ammoniumacetat", bucket: "cited" },
  { code: "E265", en: "Dehydroacetic acid", de: "Dehydracetsäure", bucket: "cited" },
  { code: "E266", en: "Sodium dehydroacetate", de: "Natriumdehydroacetat", bucket: "cited" },
  { code: "E305", en: "Ascorbyl stearate", de: "Ascorbylstearat", bucket: "cited" },
  { code: "E313", en: "Ethyl gallate", de: "Ethylgallat", bucket: "cited" },
  { code: "E314", en: "Guaiac resin", de: "Guajakharz", bucket: "cited" },
  { code: "E317", en: "Potassium erythorbate", de: "Kaliumerythorbat", bucket: "cited" },
  { code: "E318", en: "Calcium erythorbate", de: "Calciumerythorbat", bucket: "cited" },
  { code: "E323", en: "Anoxomer", de: "Anoxomer", bucket: "cited" },
  { code: "E328", en: "Ammonium lactate", de: "Ammoniumlactat", bucket: "cited" },
  { code: "E329", en: "Magnesium lactate", de: "Magnesiumlactat", bucket: "cited" },
  { code: "E342", en: "Ammonium phosphates", de: "Ammoniumphosphate", bucket: "cited" },
  { code: "E344", en: "Lecithin citrate", de: "Lecithincitrat", bucket: "cited" },
  { code: "E349", en: "Ammonium malate", de: "Ammoniummalat", bucket: "cited" },
  { code: "E359", en: "Ammonium adipate", de: "Ammoniumadipat", bucket: "cited" },
  { code: "E365", en: "Sodium fumarate", de: "Natriumfumarat", bucket: "cited" },
  { code: "E366", en: "Potassium fumarate", de: "Kaliumfumarat", bucket: "cited" },
  { code: "E367", en: "Calcium fumarate", de: "Calciumfumarat", bucket: "cited" },
  { code: "E368", en: "Ammonium fumarate", de: "Ammoniumfumarat", bucket: "cited" },
  { code: "E370", en: "1,4-Heptonolactone", de: "1,4-Heptonolacton", bucket: "cited" },
  { code: "E375", en: "Niacin", de: "Niacin", bucket: "cited" },
  { code: "E381", en: "Ammonium ferric citrate", de: "Ammoniumeisencitrat", bucket: "cited" },
  { code: "E383", en: "Calcium glycerylphosphate", de: "Calciumglycerylphosphat", bucket: "cited" },
  { code: "E384", en: "Isopropyl citrate", de: "Isopropylcitrat", bucket: "cited" },
  { code: "E386", en: "Disodium EDTA", de: "Dinatrium-EDTA", bucket: "cited" },
  { code: "E387", en: "Oxystearin", de: "Oxystearin", bucket: "cited" },
  { code: "E388", en: "Thiodipropionic acid", de: "Thiodipropionsäure", bucket: "cited" },
  { code: "E389", en: "Dilauryl thiodipropionate", de: "Dilaurylthiodipropionat", bucket: "cited" },
  { code: "E390", en: "Distearyl thiodipropionate", de: "Distearylthiodipropionat", bucket: "cited" },
  { code: "E391", en: "Phytic acid", de: "Phytinsäure", bucket: "cited" },
  { code: "E399", en: "Calcium lactobionate", de: "Calciumlactobionat", bucket: "cited" },
  { code: "E409", en: "Arabinogalactan", de: "Arabinogalactan", bucket: "cited" },
  { code: "E419", en: "Gum ghatti", de: "Ghatti-Gummi", bucket: "cited" },
  { code: "E424", en: "Curdlan", de: "Curdlan", bucket: "cited" },
  { code: "E429", en: "Peptones", de: "Peptone", bucket: "cited" },
  { code: "E430", en: "Polyoxyethylene (8) stearate", de: "Polyoxyethylen(8)-stearat", bucket: "cited" },
  { code: "E443", en: "Brominated vegetable oil", de: "Bromierte Pflanzenöle", bucket: "cited" },
  { code: "E446", en: "Succistearin", de: "Succistearin", bucket: "cited" },
  { code: "E467", en: "Ethyl hydroxyethyl cellulose", de: "Ethylhydroxyethylcellulose", bucket: "cited" },
  { code: "E472g", en: "Succinylated monoglycerides", de: "Succinylierte Monoglyceride", bucket: "cited" },
  { code: "E478", en: "Lactylated fatty acid esters of glycerol and propane-1,2-diol", de: "Lactylierte Fettsäureester von Glycerin und Propylenglycol", bucket: "cited" },
  { code: "E480", en: "Dioctyl sodium sulfosuccinate", de: "Dioctylnatriumsulfosuccinat", bucket: "cited" },
  { code: "E485", en: "Sodium stearoyl fumarate", de: "Natriumstearylfumarat", bucket: "cited" },
  { code: "E486", en: "Calcium stearoyl fumarate", de: "Calciumstearylfumarat", bucket: "cited" },
  { code: "E488", en: "Ethoxylated mono- and diglycerides", de: "Ethoxylierte Mono- und Diglyceride", bucket: "cited" },
  { code: "E489", en: "Methyl glucoside-coconut oil ester", de: "Methylglucosid-Kokosölester", bucket: "cited" },
  { code: "E490", en: "Propane-1,2-diol", de: "Propylenglycol", bucket: "cited" },
  { code: "E496", en: "Sorbitan trioleate", de: "Sorbitantrioleat", bucket: "cited" },
  { code: "E497", en: "Polyoxypropylene-polyoxyethylene polymers", de: "Polyoxypropylen-Polyoxyethylen-Polymere", bucket: "cited" },
  { code: "E498", en: "Polyglycerol esters of polycondensed castor oil fatty acids", de: "Polyglycerinester polykondensierter Ricinusfettsäuren", bucket: "cited" },
  { code: "E505", en: "Ferrous carbonate", de: "Eisencarbonat", bucket: "cited" },
  { code: "E518", en: "Magnesium sulphate", de: "Magnesiumsulfat", bucket: "cited" },
  { code: "E519", en: "Copper(II) sulphate", de: "Kupfersulfat", bucket: "cited" },
  { code: "E537", en: "Ferrous hexacyanomanganate", de: "Eisenhexacyanomanganat", bucket: "cited" },
  { code: "E539", en: "Sodium thiosulphate", de: "Natriumthiosulfat", bucket: "cited" },
  { code: "E540", en: "Dicalcium diphosphate", de: "Dicalciumdiphosphat", bucket: "cited" },
  { code: "E543", en: "Calcium sodium polyphosphate", de: "Calciumnatriumpolyphosphat", bucket: "cited" },
  { code: "E544", en: "Calcium polyphosphate", de: "Calciumpolyphosphat", bucket: "cited" },
  { code: "E545", en: "Ammonium polyphosphate", de: "Ammoniumpolyphosphat", bucket: "cited" },
  { code: "E550", en: "Sodium silicates", de: "Natriumsilicate", bucket: "cited" },
  { code: "E557", en: "Zinc silicate", de: "Zinksilicat", bucket: "cited" },
  { code: "E572", en: "Magnesium stearate", de: "Magnesiumstearat", bucket: "cited" },
  { code: "E580", en: "Magnesium gluconate", de: "Magnesiumgluconat", bucket: "cited" },
  { code: "E636", en: "Maltol", de: "Maltol", bucket: "cited" },
  { code: "E637", en: "Ethyl maltol", de: "Ethylmaltol", bucket: "cited" },
  { code: "E906", en: "Benzoin gum", de: "Benzoeharz", bucket: "cited" },
  { code: "E908", en: "Rice bran wax", de: "Reiskleiewachs", bucket: "cited" },
  { code: "E909", en: "Spermaceti wax", de: "Walrat", bucket: "cited" },
  { code: "E910", en: "Wax esters", de: "Wachsester", bucket: "cited" },
  { code: "E911", en: "Methyl esters of fatty acids", de: "Fettsäuremethylester", bucket: "cited" },
  { code: "E915", en: "Esters of colophony", de: "Kolophoniumester", bucket: "cited" },
  { code: "E916", en: "Calcium iodate", de: "Calciumiodat", bucket: "cited" },
  { code: "E917", en: "Potassium iodate", de: "Kaliumiodat", bucket: "cited" },
  { code: "E918", en: "Nitrogen oxides", de: "Stickstoffoxide", bucket: "cited" },
  { code: "E919", en: "Nitrosyl chloride", de: "Nitrosylchlorid", bucket: "cited" },
  { code: "E922", en: "Potassium persulphate", de: "Kaliumpersulfat", bucket: "cited" },
  { code: "E923", en: "Ammonium persulphate", de: "Ammoniumpersulfat", bucket: "cited" },
  { code: "E924", en: "Potassium bromate", de: "Kaliumbromat", bucket: "cited" },
  { code: "E925", en: "Chlorine", de: "Chlor", bucket: "cited" },
  { code: "E926", en: "Chlorine dioxide", de: "Chlordioxid", bucket: "cited" },
  { code: "E927a", en: "Azodicarbonamide", de: "Azodicarbonamid", bucket: "cited" },
  { code: "E928", en: "Benzoyl peroxide", de: "Benzoylperoxid", bucket: "cited" },
  { code: "E929", en: "Acetone peroxide", de: "Acetonperoxid", bucket: "cited" },
  { code: "E930", en: "Calcium peroxide", de: "Calciumperoxid", bucket: "cited" },
  { code: "E940", en: "Dichlorodifluoromethane", de: "Dichlordifluormethan", bucket: "cited" },
  { code: "E945", en: "Chloropentafluoroethane", de: "Chlorpentafluorethan", bucket: "cited" },
  { code: "E946", en: "Octafluorocyclobutane", de: "Octafluorcyclobutan", bucket: "cited" },
  { code: "E956", en: "Alitame", de: "Alitam", bucket: "cited" },
  { code: "E958", en: "Glycyrrhizin", de: "Glycyrrhizin", bucket: "cited" },
  { code: "E1001", en: "Choline salts", de: "Cholinsalze", bucket: "cited" },
  { code: "E1100", en: "Amylase", de: "Amylase", bucket: "cited" },
  { code: "E1101", en: "Proteases", de: "Proteasen", bucket: "cited" },
  { code: "E1102", en: "Glucose oxidase", de: "Glucoseoxidase", bucket: "cited" },
  { code: "E1104", en: "Lipases", de: "Lipasen", bucket: "cited" },
  { code: "E1400", en: "Dextrin", de: "Dextrin", bucket: "cited" },
  { code: "E1401", en: "Acid-treated starch", de: "Säurebehandelte Stärke", bucket: "cited" },
  { code: "E1402", en: "Alkaline-treated starch", de: "Alkalisch behandelte Stärke", bucket: "cited" },
  { code: "E1403", en: "Bleached starch", de: "Gebleichte Stärke", bucket: "cited" },
  { code: "E1405", en: "Enzyme-treated starch", de: "Enzymbehandelte Stärke", bucket: "cited" },
  { code: "E1411", en: "Distarch glycerol", de: "Distärkeglycerin", bucket: "cited" },
  { code: "E1421", en: "Starch acetate (vinyl acetate)", de: "Stärkeacetat (Vinylacetat)", bucket: "cited" },
  { code: "E1423", en: "Acetylated distarch glycerol", de: "Acetyliertes Distärkeglycerin", bucket: "cited" },
  { code: "E1430", en: "Distarch glycerine", de: "Distärkeglycerin", bucket: "cited" },
  { code: "E1441", en: "Hydroxypropyl distarch glycerine", de: "Hydroxypropyldistärkeglycerin", bucket: "cited" },
  { code: "E1443", en: "Hydroxypropyl distarch glycerol", de: "Hydroxypropyldistärkeglycerin", bucket: "cited" },
  { code: "E1501", en: "Benzylated hydrocarbons", de: "Benzylierte Kohlenwasserstoffe", bucket: "cited" },
  { code: "E1502", en: "Butane-1,3-diol", de: "Butan-1,3-diol", bucket: "cited" },
  { code: "E1503", en: "Castor oil", de: "Rizinusöl", bucket: "cited" },
  { code: "E1504", en: "Ethyl acetate", de: "Ethylacetat", bucket: "cited" },
  { code: "E1510", en: "Ethanol", de: "Ethanol", bucket: "cited" },
  { code: "E1516", en: "Glyceryl monoacetate", de: "Glycerinmonoacetat", bucket: "cited" },
  { code: "E1525", en: "Hydroxyethyl cellulose", de: "Hydroxyethylcellulose", bucket: "cited" },
];

/** @param {Bucket} bucket */
export function extrasIn(bucket) {
  return EXTRAS.filter((row) => row.bucket === bucket).map((row) => row.code);
}
